### ISSUE TITLE
Add social media links

### ISSUE THREAD

**Issue by clemsos** [valentina-project/valentina-project.github.io#4]

**Comment by clemsos** [comment]
added in 1b02183 . Facebook, G+, twitter and youtube :  is that not too much ? what is the most important one ? Twitter ?

**Comment by tusuzu** [comment]
G+ page is dead.
Facebook is for users and has the most activity (900)
Twitter connects mostly with other related projects (231 - @ValentinaPSW,
378 - @SewBuzzed)
YouTube is for Valentina training (216)

**Comment by rejon** [comment]
Yep good nuke g+
