### ISSUE TITLE
Link for developers

### ISSUE THREAD

**Issue by clemsos** [valentina-project/valentina-project.github.io#5]
link to the bitbucket page : http://valentinaproject.bitbucket.org/index.html#source

**Comment by clemsos** [comment]
solved in 7d2438026bb8789096b335a2a080ac9c958539d8

**Comment by tusuzu** [comment]
Hey Clement,
I will solve this properly later, but there is a redirect loop to
valentina-project.org
Can we delete the CNAME file? Perhaps there is a better way.
Dreamhost points to valentina-project.github.io for now.

Best,
susan

**Comment by clemsos** [comment]
yes, sure ! It was working for a while though... Anyway, I deleted the CNAME for now
