### ISSUE TITLE
Move social link icons to top of page

### ISSUE THREAD

**Issue by tusuzu** [valentina-project/valentina-project.github.io#6]
I like the clean approach of our website, but I've met lots of people who don't notice the little icons at the bottom of the page.

Moving the links for twitter, etc. to the top of the page is an easy fix.

**Comment by rejon** [comment]
Hmmm but are those people the target audience? I think they look good where
they are at. The flow makes sense to go from someone who doesnt know the
software all the way down thru features to the end where they are intrigued
enough to join the conversation.

Another idea what about making a twitter widget with latest tweets and
expanding the social section?

Jon

**Comment by tusuzu** [comment]
They are the people from fashion hack day berlin and open tech summit berlin

**Comment by clemsos** [comment]
Agree with Jon that the links at the bottom make sense as a continuation for reading. We can add a better interaction though. Not sure about a whole twitter feed but maybe a follow button + a like button for Facebook (instead of a link) ?

**Comment by rejon** [comment]
Yeah like that, promotes action

**Comment by tusuzu** [comment]
Yeah the problem was that people would go to the page and not know what to
do other than download the code. Because they're not computer people,
they're fashion people.

**Comment by tusuzu** [comment]
Closed issue.
